name: Greetings

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Memer Action
        id: memer

        uses: Bhupesh-V/memer-action@master
        with:
          filter: 'new'

      - name: Check Outputs
        run: |
          echo "${{ steps.memer.outputs.meme }}"
          echo "${{ steps.memer.outputs.title }}"
          echo "${{ steps.memer.outputs.source }}"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1.3.0
        id: create_comment
        with:
          comment-author: 'fairdataihub-bot'
          issue-number: ${{ github.event.number }}
          body: |
            ðŸŽ‰ðŸŽ‰ Thanks for opening this PR/Issue ðŸ¤—
            Please wait while the maintainer(s) review it

            Meanwhile have a look at this while you wait ðŸ˜:

            > **${{ steps.memer.outputs.title }}**
            ![meme](${{ steps.memer.outputs.meme }})
